mail-in-a-pods:
  global:
    primaryHostname: mailer4.kuprin.su
    storageClass: vultr-block-storage
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/system-workloads: ""
    tolerations:
    - key: node-role
      operator: Equal
      value: system-workloads
      effect: NoExecute

  mailinabox:
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/log-workloads: ""
    tolerations:
    - key: node-role
      operator: "Equal"
      value: log-workloads #Change to dex-app-workloads
      effect: NoExecute
    storage:
      size: 50Gi

  bind:
    # It is disabled by default
    storage:
      size: 10Gi

  nsd:
    storage:
      size: 10Gi

    service:
      type: NodePort
      nodePort:
        udp: 32767
        tcp: 32767

  gateway:
    httpPlaceholder:
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/log-workloads: ""
      tolerations:
      - key: node-role
        operator: "Equal"
        value: log-workloads #Change to dex-app-workloads
        effect: NoExecute

  certManager:
    acme:
      server: https://acme-staging-v02.api.letsencrypt.org/directory # Use for staging
      email: "admin@opendops.tech"
      http01:
        nodeSelector:
          kubernetes.io/os: linux
          node-role.kubernetes.io/system-workloads: ""
        tolerations:
        - key: node-role
          operator: Equal
          value: system-workloads
          effect: NoExecute